import archiver from "archiver";
import { getGenerationById } from "../db/database";

export async function createZipArchive(id: string) {
  const generation = getGenerationById(id);
  if (!generation) return null;

  const archive = archiver("zip", { zlib: { level: 9 } });

  // Add Terraform files
  if (generation.terraform) {
    archive.append(generation.terraform, { name: "main.tf" });
  }

  // Add Ansible files
  if (generation.ansible) {
    archive.append(generation.ansible, { name: "playbook.yml" });
  }

  // Add Architecture documentation
  if (generation.architecture) {
    const archDoc = buildArchitectureDoc(generation.architecture, generation.description, generation.provider);
    archive.append(archDoc, { name: "ARCHITECTURE.md" });
  }

  // Add README
  const readme = buildReadme(generation);
  archive.append(readme, { name: "README.md" });

  return archive;
}

function buildArchitectureDoc(architecture: string, description: string, provider: string): string {
  // Extract sections from the architecture content
  const mermaidMatch = architecture.match(/---MERMAID---([\s\S]*?)---END-MERMAID---/);
  const componentsMatch = architecture.match(/---COMPONENTS---([\s\S]*?)---END-COMPONENTS---/);
  const flowMatch = architecture.match(/---FLOW---([\s\S]*?)---END-FLOW---/);

  const mermaidDiagram = mermaidMatch ? mermaidMatch[1].trim() : "";
  const components = componentsMatch ? componentsMatch[1].trim() : "";
  const flow = flowMatch ? flowMatch[1].trim() : "";

  return `# Architecture Documentation

## Overview

**Description:** ${description}
**Cloud Provider:** ${provider.toUpperCase()}
**Generated by:** InfraSketch AI

---

## Architecture Diagram

\`\`\`mermaid
${mermaidDiagram}
\`\`\`

> **Note:** Paste this diagram into any Mermaid-compatible viewer (GitHub, VS Code, Notion, etc.) to see the visual representation.

---

## Component Inventory

${components}

---

## Data Flow

${flow}

---

## Naming Convention

All resources follow this naming pattern:

\`\`\`
{project}-{environment}-{service}-{resource-type}
\`\`\`

**Examples:**
- VPC: \`myapp-prod-vpc\`
- Public Subnet: \`myapp-prod-public-us-east-1a\`
- Private App Subnet: \`myapp-prod-private-app-us-east-1a\`
- Private DB Subnet: \`myapp-prod-private-db-us-east-1a\`
- ALB: \`myapp-prod-alb\`
- ECS Cluster: \`myapp-prod-ecs-cluster\`
- RDS Instance: \`myapp-prod-wordpress-db\`
- Security Groups: \`myapp-prod-{tier}-sg\`

## Security Architecture

### Network Tiers

| Tier | Subnet Type | Internet Access | Contains |
|------|-------------|-----------------|----------|
| Public | Public Subnets | Direct (IGW) | ALB, NAT Gateway |
| Application | Private App Subnets | Outbound only (NAT) | ECS Tasks, App Servers |
| Database | Private DB Subnets | None | RDS, ElastiCache |

### Security Group Chain

\`\`\`
Internet → [ALB-SG: 80/443] → [APP-SG: app-port from ALB-SG only] → [DB-SG: db-port from APP-SG only]
\`\`\`

No resource in a lower tier can be accessed directly from the internet. Traffic must flow through the security group chain.
`;
}

function buildReadme(generation: any): string {
  return `# Generated Infrastructure Code

## Description
${generation.description}

## Provider
${generation.provider.toUpperCase()}

## Type
${generation.outputType}

## Generated At
${generation.createdAt}

## Files Included

| File | Description |
|------|-------------|
${generation.terraform ? "| main.tf | Terraform infrastructure configuration |\n" : ""}${generation.ansible ? "| playbook.yml | Ansible automation playbook |\n" : ""}| ARCHITECTURE.md | Architecture diagram, component list, and naming conventions |
| README.md | This file |

## Usage

${generation.terraform ? `### Terraform
\`\`\`bash
# Initialize Terraform
terraform init

# Preview changes (review before applying!)
terraform plan

# Apply infrastructure
terraform apply

# Destroy when done
terraform destroy
\`\`\`
` : ""}
${generation.ansible ? `### Ansible
\`\`\`bash
# Run the playbook
ansible-playbook -i inventory/hosts.yml playbook.yml

# Dry run first
ansible-playbook -i inventory/hosts.yml playbook.yml --check
\`\`\`
` : ""}

## Important Notes

- Review ALL generated code before applying to production
- Update variable values in terraform.tfvars as needed
- Ensure proper cloud credentials are configured
- See ARCHITECTURE.md for the full component diagram and naming conventions
`;
}
